---
  output: github_document
---
  
  <!-- README.md is generated from README.Rmd. Please edit that file -->
  
# lidRmetrics
Additional point cloud metrics to use with *_metric functions in lidR. 


## Installation 

You can install the most recent version of the package by executing the code below:

```{r, eval=FALSE}
devtools::install_github("ptompalski/lidRmetrics")
library(lidRmetrics)
```


## Example usage

All of the functions in `lidRmetrics` are designed to be used with one of the *_metrics functions in the `lidR` package (e.g. `grid_metrics()`). 

For example:

```{r, eval=FALSE}
library(lidR)
library(lidRmetrics)

LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
las <- readLAS(LASfile, select = "*", filter = "-keep_random_fraction 0.5")

m1 <- cloud_metrics(las, ~metrics_basic(Z))

m2 <- grid_metrics(las, ~metrics_set1(Z), res = 20)

m3 <- grid_metrics(las, ~metrics_set2(X, Y, Z), res = 20)
```

## List of metrics


```{r, echo=F, message=FALSE}
library(readxl)
library(knitr)
library(tidyverse)

# rmarkdown::pandoc_options(to = "md",args = "-all_symbols_escapable")

mtrxs <- readxl::read_excel("list_of_metrics.xlsx")

# names(mtrxs)[3] <- knitr::inline_expr("metrics_* function")
# mtrxs <- mtrxs %>% mutate(`Metrics name` = paste0("`",`Metrics name`,"`"))


options(knitr.kable.NA = '')
# kable(mtrxs, format = "html") #promissing
# pander::pander(mtrxs, split.tables=Inf, split.cells = c(10, 25, 15, 40),
#                          style="rmarkdown", missing="")

kable_out <- knitr::kable(mtrxs, "html")
readr::write_file(kable_out, "kable_out.html")


```



```{r, echo=FALSE}
htmltools::includeHTML("kable_out.html")
```


